---
- hosts: georep_master
  remote_user: root
  gather_facts: no

  tasks:
  - name: Create the geo-rep session
    geo_rep: action=create
            mastervol="{{ mastervolname }}"
            slavevol="{{ slavevol }}"
            force="{{ force }}"
            georepuser="{{ georepuser }}"

  - name: Configure the meta-volume for geo-replication
    command: gluster volume geo-replication "{{ mastervolname }}" "{{slave[0]}}::{{slavevolname}}" config use_meta_volume true

