---
- hosts: gluster_servers
  remote_user: root
  gather_facts: no
  vars:
    opts: "inode64,noatime,nodiratime"

  tasks:
  - name: Create the backend disks, skips if present
    file: path={{ item.path }} state=directory
    with_items: "{{ mntpath }}"

  - name: Set mount options for VDO
    set_fact:
      opts: "{{opts}},x-systemd.requires=vdo.service"
    when: vdo_device is defined and vdo_device|bool == true

  - name: Mount the logical volumes
    mount: name={{ item.path }} src={{ item.device }} fstype=xfs
           opts="{{ opts }}" state=mounted
    with_items: "{{ mntpath }}"
