---
- hosts: gluster_servers
  remote_user: root
  gather_facts: no
  vars:
    opts: "inode64,noatime,nodiratime"

  tasks:
  - name: Create the mountpoints, skips if present
    file: path={{ item.path }} state=directory
    with_items: "{{ mntpath }}"

  - name: Set mount options for VDO
    set_fact:
      vdo_opts: "{{opts}},x-systemd.requires=vdo.service"
    when: mntpath[0].vdodev is defined and mntpath[0].vdodev|bool == True

  - name: Mount the vdo disks (if any)
    mount: name={{ item.path }} src={{ item.device }} fstype=xfs
           opts="{{ vdo_opts }}" state=mounted
    with_items: "{{ mntpath }}"
    when: item.vdodev is defined and item.vdodev|bool == True

  - name: Mount the disks (non-vdo)
    mount: name={{ item.path }} src={{ item.device }} fstype=xfs
           opts="{{ opts }}" state=mounted
    with_items: "{{ mntpath }}"
    when: item.vdodev is not defined