---
- hosts: gluster_servers
  remote_user: root
  gather_facts: no

  tasks:

  - name: Add confs to glusterd.vol
    lineinfile:
        dest=/etc/glusterfs/glusterd.vol
        line="    option rpc-auth-allow-insecure on"
        insertbefore='end-volume'

  - name: Restart glusterd services
    service: name=glusterd state=restarted

  - name: Create a new user
    user: name="{{ smb_username }}"
    when: smb_username is defined

  - name: Enable volume option user.smb
    command: gluster volume set {{ volname }} user.smb enable
    delegate_to: "{{ master }}"
    run_once: true

  - name: Set group samba option on the volume
    command: gluster volume set {{ volname }} group samba
    delegate_to: "{{ master }}"
    run_once: true

  - name: Set smb password
    raw: (echo {{ smb_password }}; echo {{ smb_password }}) | smbpasswd -s -a "{{ smb_username }}"
    when: smb_password is defined and smb_username is defined
